# Generated by Django 4.2 on 2023-04-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guitar",
            fields=[
                (
                    "numero_serie",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("preco", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "fabricante",
                    models.CharField(
                        choices=[
                            ("Fender", "Fender"),
                            ("Martin", "Martin"),
                            ("Gibson", "Gibson"),
                            ("Collings", "Collings"),
                            ("Olson", "Olson"),
                            ("Ryan", "Ryan"),
                            ("PRS", "PRS"),
                            ("Any", "Any"),
                        ],
                        default="Any",
                        max_length=50,
                    ),
                ),
                ("modelo", models.CharField(max_length=50)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("Acustico", "Acustico"), ("Eletrico", "Eletrico")],
                        default="Acustico",
                        max_length=50,
                    ),
                ),
                (
                    "madeira_tampo",
                    models.CharField(
                        choices=[
                            ("Indian Rosewood", "Indian Rosewood"),
                            ("Brazilian Rosewood", "Brazilian Rosewood"),
                            ("Mahogany", "Mahogany"),
                            ("Maple", "Maple"),
                            ("Cocobolo", "Cocobolo"),
                            ("Cedar", "Cedar"),
                            ("Adirondack", "Adirondack"),
                            ("Alder", "Alder"),
                            ("Sitka", "Sitka"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "madeira_fundo",
                    models.CharField(
                        choices=[
                            ("Indian Rosewood", "Indian Rosewood"),
                            ("Brazilian Rosewood", "Brazilian Rosewood"),
                            ("Mahogany", "Mahogany"),
                            ("Maple", "Maple"),
                            ("Cocobolo", "Cocobolo"),
                            ("Cedar", "Cedar"),
                            ("Adirondack", "Adirondack"),
                            ("Alder", "Alder"),
                            ("Sitka", "Sitka"),
                        ],
                        max_length=50,
                    ),
                ),
                ("foto", models.ImageField(blank=True, upload_to="guitars/")),
            ],
        ),
    ]
