# Generated by Django 4.2 on 2023-05-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guitar",
            name="foto",
            field=models.ImageField(blank=True, upload_to="guitars"),
        ),
    ]
