# Generated by Django 4.2 on 2023-05-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_guitar_modelo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guitar",
            name="tipo",
            field=models.CharField(
                choices=[("Acustico", "Acustico"), ("Eletrico", "Eletrico")],
                default="Eletrico",
                max_length=50,
            ),
        ),
    ]
